# Loader metadata
modLoader="javafml" # mandatory
loaderVersion="[31,)" # mandatory
#issueTrackerURL="http://my.issue.tracker/"

# TFC
[[mods]]
    modId="tfc" # mandatory
    version="${file.jarVersion}" #mandatory
    displayName="TerraFirmaCraft" #mandatory
    # A URL to query for updates for this mod. See the JSON update specification <here>
    #updateJSONURL="http://myurl.me/" #optional
    # A URL for the "homepage" for this mod, displayed in the mod UI
    #displayURL="http://example.com/" #optional
    # A file name (in the root of the mod JAR) containing a logo for display
    #logoFile="examplemod.png" #optional
    # A text field displayed in the mod UI
    credits="Made by AlcatrazEscapee" #optional
    # A text field displayed in the mod UI
    #authors="Love, Cheese and small house plants" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description='''TerraFirmaCraft - The Next Generation'''

# Dependencies
[[dependencies.tfc]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"